name: Generate SchemaVersions

on:
  repository_dispatch:
    types: schema-updated
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Holistic Event Repo
        uses: actions/checkout@v4
        with:
          path: rewards-holistic-events

      - name: Checkout Mock Schema Registrar
        uses: actions/checkout@v4
        with:
          repository: rr-weiyi-yu/Mock-Schema-Registrar
          token: ${{ secrets.MySecret }}
          path: Mock-Schema-Registrar

      - name: Copy schema_versions.json
        run: |
          cp Mock-Schema-Registrar/schema_versions.json rewards-holistic-events/shared/src/commonMain/resources/schema_versions/schema_versions.json
          if [ $? -eq 0 ]; then
            echo "File copied successfully"
          else
            echo "Failed to copy file"
            exit 1
          fi

      - name: Generate SchemaVersions
        working-directory: rewards-holistic-events
        run: ./gradlew generateSchemaVersions