# This is a basic workflow to help you get started with Actions

name: Generate SchemaVersions

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [shcema-updated]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Holistic Event Repo
        uses: actions/checkout@v4

      - name: Fetch schema_versions.json
        run: |
          git clone https://github.com/rr-weiyi-yu/Mock-Schema-Registrar.git
          cp Mock-Schema-Registrar/schema_versions.json .

      # Runs a single command using the runners shell
      - name: Generate SchemaVersions
        run: ./gradlew generateSchemaVersions
