name: Generate SchemaVersions

on:
  repository_dispatch:
    types: schema-updated
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Holistic Event Repo
        uses: actions/checkout@v4
        with:
          path: rewards-holistic-events

      - name: Checkout Mock Schema Registrar
        uses: actions/checkout@v4
        with:
          repository: rr-weiyi-yu/Mock-Schema-Registrar
          token: ${{ secrets.MySecret }}
          path: Mock-Schema-Registrar

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # or whichever version you're using
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Copy schema_versions.json
        run: |
          cp Mock-Schema-Registrar/schema_versions.json rewards-holistic-events/shared/src/commonMain/resources/schema_versions/schema_versions.json
          if [ $? -eq 0 ]; then
            echo "File copied successfully"
          else
            echo "Failed to copy file"
            exit 1
          fi

      - name: Generate SchemaVersions
        working-directory: rewards-holistic-events
        run: |
          ./gradlew generateSchemaVersions
          rm shared/src/commonMain/resources/schema_versions/schema_versions.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.MySecret }}
          commit-message: Update SchemaVersions
          title: '[Automated] Update SchemaVersions'
          body: |
            This is an automated pull request to update SchemaVersions.kt.
          branch: automated-update
          path: rewards-holistic-events
          base: main
